;;; -*- lexical-binding: t -*-

(deftheme phosphors "A theme like old fashion phosphors.")

(custom-theme-set-faces
 'phosphors
 `(default                        ((((type tty)))
																	 (((type graphic))
																		:background "#282828"
																		:foreground "#33ff00")))
 `(hl-line                        ((((type graphic)))
																	 (((type tty)))))
 `(cursor                         ((t (:background "#33ff00"))))
 '(region                         ((t (:underline "#ff0000"))))
 `(font-lock-comment-face         ((t (:foreground "#ffb000" :extend t))))
 `(font-lock-doc-face             ((t (:foreground "#ffb000" :extend t))))
 `(font-lock-warning-face         ((t (:foreground "red"))))
 `(font-lock-string-face          ((t (:foreground "#ffcc00"))))
 `(font-lock-function-name-face   ((t (:background "#282890"))))
 `(font-lock-keyword-face         ((t (:background "#284028"))))
 `(font-lock-constant-face        ((t (:background "#3d3900"))))
 `(font-lock-builtin-face         ((t ())))
 `(font-lock-variable-name-face   ((t ())))
 `(font-lock-type-face            ((t ())))
 `(font-lock-preprocessor-face    ((t (:inherit font-lock-constant-face))))
 `(highlight                      ((t (:background "#283e28"))))
 `(company-tooltip-common         ((t ())))
 `(company-tooltip-common-selection ((t (:inherit font-lock-constant-face :inverse-video t))))
 `(company-tooltip                ((t (:background "#336633"))))
 `(company-tooltip-selection      ((t (:inherit font-lock-constant-face :inverse-video t))))
 `(company-tooltip-annotation     ((t (:inherit font-lock-comment-face))))
 `(company-scrollbar-bg           ((t (:background "#303030"))))
 `(company-scrollbar-fg           ((t (:background "#4E4E4E"))))
 '(meow-keypad-indicator          ((t ())))
 '(meow-insert-indicator          ((t ())))
 '(meow-normal-indicator          ((t ())))
 '(meow-motion-indicator          ((t ())))
 '(meow-keypad-cursor             ((t (:inherit cursor))))
 '(meow-insert-cursor             ((t (:inherit cursor))))
 '(meow-normal-cursor             ((t (:inherit cursor))))
 '(meow-motion-cursor             ((t (:inherit cursor))))
 '(dired-directory                ((t (:bold t))))
 '(mode-line                      ((t (:bold t))))
 '(mode-line-inactive             ((t (:bold t))))
 `(parenthesis                    ((t (:foreground "#909090"))))
 '(highlight-symbol-face          ((t ())))
 '(yascroll:thumb-fringe          ((t (:background "#606060" :foreground "#606060"))))
 '(yascroll:thumb-text-area       ((t (:background "#606060" :foreground "#606060"))))
 '(rime-indicator-face            ((t (:foreground "#1853cc"))))
 '(rime-indicator-dim-face        ((t ())))
 '(rime-default-face              ((t (:foreground "#303030" :background "#ececec"))))
 '(rime-preedit-face              ((t (:inverse-video nil :underline t))))
 '(rime-cursor-face               ((t (:inherit font-lock-constant-face))))
 '(rime-candidate-num-face        ((t ())))
 '(rime-comment-face              ((t ())))
 '(rime-indicator-face            ((t (:foreground "#713da6"))))
 '(telega-entity-type-code        ((t (:inherit fixed-pitch))))
 '(telega-entity-type-pre         ((t (:inherit fixed-pitch))))
 '(cider-fringe-good-face         ((t (:foreground "#33ff33"))))
 '(web-mode-html-attr-name-face   ((t ())))
 '(web-mode-html-tag-face         ((t ())))
 '(fringe                         ((t ())))
 `(line-number                    ((t (:foreground "#339933"))))
 `(line-number-current-line       ((((type graphic)) :inherit hl-line)
																	 (t (:bold t :background "#ffffff"))))
 '(mc/cursor-bar-face             ((t (:background "grey50" :height 1))))
 '(dired-subtree-depth-1-face     ((t (:background "grey90"))))
 '(dired-subtree-depth-2-face     ((t (:background "grey80"))))
 '(dired-subtree-depth-3-face     ((t (:background "grey70"))))
 '(dired-subtree-depth-4-face     ((t (:background "grey90"))))
 '(dired-subtree-depth-5-face     ((t (:background "grey80"))))
 '(dired-subtree-depth-6-face     ((t (:background "grey70"))))
 '(minibuffer-prompt              ((t (:foreground "#ffcc00"))))
 '(web-mode-function-call-face    ((t ())))
 '(web-mode-function-name-face    ((t ())))
 '(web-mode-html-tag-face         ((t (:bold t))))
 '(window-divider                 ((t ())))
 '(vertical-border                ((t (:foreground "#33ff00"))))
 '(web-mode-html-tag-bracket-face ((t (:inherit parenthesis)))))

(and load-file-name
		 (boundp 'custom-theme-load-path)
		 (add-to-list 'custom-theme-load-path
									(file-name-as-directory
									 (file-name-directory load-file-name))))

(provide-theme 'phosphors)
;;; phosphors-theme.el ends here
